n1=input("Enter the first number: ")
n2=input("Enter the second number: ")
n1=int(n1)
n2=int(n2)
print("Addition: ",n1+n2)
print("Subtraction: ",n1-n2)
print("Multiplication: ",n1*n2)
print("Subtraction: ",n1/n2)